/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexio;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Budha
 */
public class ComentariosJuego extends javax.swing.JDialog {

    DefaultTableModel modelo;
    private String NombreJuego;
    
    /**
     * Creates new form ComentariosJuego
     */
    
    /**
     * Passam per parametre un string amb el nom de joc i amb el dni. Inicialitzam les variables en el constructor.
     * 
     * @param parent
     * @param modal
     * @param NombreJuego
     * @param Dni 
     */
    public ComentariosJuego(java.awt.Frame parent, boolean modal,String NombreJuego) { 
        super(parent, modal);
        this.NombreJuego = NombreJuego;
        initComponents();
        this.setTitle("Comentarios juegos");
        this.getContentPane().setBackground(new Color (243,245,246));
        verComentarios();
    }
    
    /**
     * Feim una select del Nom de usuario, el comentari que tengui el dni i el nom de la variable global.
     * Aquest valors els agafam de la taula consultar juego, amb doble click.
     */
    private void verComentarios(){
        Conexio mysql = new Conexio();
        Connection con = mysql.conectar();
        String [] titulos = {"Usuario","Puntuacion","Comentarios"};
        String [] registro = new String[3];
         DefaultTableModel modelo = new DefaultTableModel(null,titulos);
        String sSQL = "";

        sSQL = "Select u.NombreUsuario,c.Puntuacion,c.Comentario "
                +"from usuarios u inner join calificaciones c "
                + "on u.Dni = c.Usuarios_Dni "
                +"where c.Juegos_NombreJuego = '"+NombreJuego+"'";
               
                
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sSQL);
            while (rs.next()) {
                
                registro[0] = rs.getString("u.NombreUsuario");
                registro[1] = rs.getString("c.Puntuacion");
                registro[2] = rs.getString("c.Comentario");
                modelo.addRow(registro);
                }
            
            jTableComentariosJuego.setModel(modelo);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        
    }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableComentariosJuego = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableComentariosJuego.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Nombre del propietario", "Comentarios"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableComentariosJuego.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableComentariosJuego);
        if (jTableComentariosJuego.getColumnModel().getColumnCount() > 0) {
            jTableComentariosJuego.getColumnModel().getColumn(0).setResizable(false);
            jTableComentariosJuego.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    /**
 
     * @param args 
     */
   
    
   
            
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableComentariosJuego;
    // End of variables declaration//GEN-END:variables
}
