/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexio;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Budha
 */
public class ConsultarJuego extends javax.swing.JDialog {
    
    DefaultTableModel modelo;
   
    /**
     * Creates new form ConsultarJuego
     */
    public ConsultarJuego(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Consultar juego");
        this.getContentPane().setBackground(new Color (243,245,246));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombreJuego = new javax.swing.JTextField();
        jTextFieldPropietario = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonMostrarTodo = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsultarJuegos = new javax.swing.JTable();
        jComboBoxPlataforma = new javax.swing.JComboBox<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre del juego");

        jLabel2.setText("Propietario");

        jLabel3.setText("Plataforma");

        jTextFieldNombreJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreJuegoActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonMostrarTodo.setText("Mostrar todo");
        jButtonMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarTodoActionPerformed(evt);
            }
        });

        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });

        jTableConsultarJuegos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Propietario", "Plataformas", "Multijugador", "Calificación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableConsultarJuegos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultarJuegosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableConsultarJuegos);
        if (jTableConsultarJuegos.getColumnModel().getColumnCount() > 0) {
            jTableConsultarJuegos.getColumnModel().getColumn(0).setResizable(false);
            jTableConsultarJuegos.getColumnModel().getColumn(1).setResizable(false);
            jTableConsultarJuegos.getColumnModel().getColumn(2).setResizable(false);
            jTableConsultarJuegos.getColumnModel().getColumn(3).setResizable(false);
            jTableConsultarJuegos.getColumnModel().getColumn(4).setResizable(false);
        }

        jComboBoxPlataforma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PS3", "PS4", "PS Vita", "PC", "MAC", "Web", "Wii", "Wii U", "3DS", "Android", "iPhone", "Xbox 360", "Xbox One" }));
        jComboBoxPlataforma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPlataformaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldNombreJuego, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(jTextFieldPropietario))
                        .addGap(30, 30, 30)
                        .addComponent(jButtonMostrarTodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(jButtonCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNombreJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMostrarTodo)
                    .addComponent(jButtonBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCerrar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxPlataformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPlataformaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPlataformaActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuPrincipal mp = new MenuPrincipal(new javax.swing.JFrame(), true);
        mp.setVisible(true);
    }//GEN-LAST:event_jButtonCerrarActionPerformed


    public void mostrarJuego() {

        String pNombreJuego = jTextFieldNombreJuego.getText();
        String pPropietario = jTextFieldPropietario.getText();
        String plataforma = jComboBoxPlataforma.getSelectedItem().toString();
        Conexio mysql = new Conexio();
        Connection con = mysql.conectar();
        String [] titulos = {"Nombre","Propietario","Plataformas","Multijugador","Calificación"};
        String[] registro = new String[5];
        modelo = new DefaultTableModel(null, titulos);
        String sSQL = "";
        
        /**
         * A la select empleam left join per agafar tots els valors tenguin o no tenguin correspondencia a un altra taula.
         * Retorna tots els valors de la taula de la esquerra mes els valors que corresposen a les columnes,i en cas de que no
         * corresposin, apareixerá null.
         * Al primer join accedim a la taula usuarios_has_juegos per obtenir el nom del joc.
         * Al segon left join accedim a la taula usuari per obtenir el nom del usuari que te algun joc asignat.
         * Al tercer i el cuart obtenim el nom de la plataforma que te asignada el joc corresponent (NombreJuego).
         * Al darrer join obtenem la calificació que te asignada el joc corresponent (NombreJuego).
         * Al where tenim 1 = 1. Es un recurs de programació per poder validar si o si una clausula where i poder afegir AND.
         * Ho emplei en aquest cas per poder concatenar les consultes nombrejuego,propietario i plataforma amb la sentencia sql.
         * i per tenir les tres variables a condicions AND.
         */
        sSQL = "select j.NombreJuego, u.NombreUsuario,p.NombrePlataforma, j.Multijugador,c.Puntuacion " //dades que s'han de mostrar
                + "from juegos j left join usuarios_has_juegos uj on j.NombreJuego = uj.Juegos_NombreJuego "
                + "left join usuarios u on u.Dni = uj.usuarios_Dni "
                + "left join juegos_has_plataformas jp on j.NombreJuego = jp.Juegos_NombreJuego "
                + "left join plataformas p on p.IdPlataforma = jp.Plataformas_IdPlataforma "
                + "left join calificaciones c on c.Juegos_NombreJuego = j.NombreJuego and c.Usuarios_Dni = u.Dni where 1=1";

        /**
         * Si el el camp nou no esta buit,continua la sentencia.
         */
        if (!pNombreJuego.isEmpty()) {
            sSQL = sSQL + " and j.NombreJuego LIKE '%" + pNombreJuego + "%'";

        }
         /**
         * Si el el camp propetario no esta buit,continua la sentencia.
         */
        if (!pPropietario.isEmpty()) {
            sSQL = sSQL + " and u.NombreUsuario LIKE '%" + pPropietario + "%'";
        }
         /**
         * Si el el camp plataforma esta seleccionat,continua la sentencia.
         */
        sSQL = sSQL + " and p.NombrePlataforma = '" + plataforma + "'";

               
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sSQL);
            while (rs.next()) {

                registro[0] = rs.getString("j.NombreJuego");
                registro[1] = rs.getString("u.NombreUsuario");
                registro[2] = rs.getString("p.NombrePlataforma");
                registro[3] = rs.getString("j.Multijugador");
                registro[4] = rs.getString("c.Puntuacion");
                modelo.addRow(registro);
            }

            jTableConsultarJuegos.setModel(modelo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }

    }
    /**
     * Per poder realitzar la consulta de comentaris a la clase comentarioJuego, necessitava l'idenfitifcador, tot i que
     * no el mostram a la taula.
     * Alhora de mostrar la taula, no apareixera el parametre Id, però el podrem emprar per realitzar la consulta desde la altre
     * clase.
     * La sentencia es la mateixa sense els filtres de joc,plataforma i propietari, per a n'aquesta consulta volem mostrar
     * tota la base de dades.
     * 
     */

    
    
    
    public void mostrarTodosJuegos(){
        Conexio mysql = new Conexio();
        Connection con = mysql.conectar();
        String [] titulos = {"Nombre","Propietario","Plataformas","Multijugador","Calificación","Id"};
        String [] registro = new String[6];
         DefaultTableModel modelo2 = new DefaultTableModel(null,titulos);
        
        
        String sSQL = "";
        sSQL ="select j.NombreJuego, u.NombreUsuario,p.NombrePlataforma, j.Multijugador,c.Puntuacion,u.Dni "
                + "from juegos j left join usuarios_has_juegos uj on j.NombreJuego = uj.Juegos_NombreJuego "
                + "left join usuarios u on u.Dni = uj.usuarios_Dni "
                + "left join juegos_has_plataformas jp on j.NombreJuego = jp.Juegos_NombreJuego "
                + "left join plataformas p on p.IdPlataforma = jp.Plataformas_IdPlataforma "
                + "left join calificaciones c on c.Juegos_NombreJuego = j.NombreJuego and c.Usuarios_Dni = u.Dni ";

         try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sSQL);
            while (rs.next()) {
                
                registro[0] = rs.getString("j.NombreJuego");
                registro[1] = rs.getString("u.NombreUsuario");
                registro[2] = rs.getString("p.NombrePlataforma");
                registro[3] = rs.getString("j.Multijugador");
                registro[4] = rs.getString("c.Puntuacion");
                registro[5] = rs.getString("u.Dni");
                modelo2.addRow(registro);
            }
            
            jTableConsultarJuegos.setModel(modelo2);
            jTableConsultarJuegos.getColumnModel().getColumn(5).setMinWidth(0);
            jTableConsultarJuegos.getColumnModel().getColumn(5).setMaxWidth(0);

            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        
        }
 
    }
    
    
    
    
    
    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here
        
        mostrarJuego();
       
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTextFieldNombreJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreJuegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreJuegoActionPerformed
    
    
  
    private void jButtonMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarTodoActionPerformed
        // TODO add your handling code here:
        mostrarTodosJuegos();
    }//GEN-LAST:event_jButtonMostrarTodoActionPerformed

    private void jTableConsultarJuegosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultarJuegosMouseClicked
        // TODO add your handling code here:
        
        if(evt.getClickCount()== 2){
            int row = jTableConsultarJuegos.rowAtPoint(evt.getPoint());

                String juego = (String) jTableConsultarJuegos.getValueAt(row, 0);
                String dni = (String) jTableConsultarJuegos.getValueAt(row, 5);
                ComentariosJuego cj = new ComentariosJuego(new javax.swing.JFrame(), true, juego, dni);
                cj.setVisible(true);
        }

    }//GEN-LAST:event_jTableConsultarJuegosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultarJuego dialog = new ConsultarJuego(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonMostrarTodo;
    private javax.swing.JComboBox<String> jComboBoxPlataforma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsultarJuegos;
    private javax.swing.JTextField jTextFieldNombreJuego;
    private javax.swing.JTextField jTextFieldPropietario;
    // End of variables declaration//GEN-END:variables
}
