/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexio;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tomeu
 */
public class VerJuego extends javax.swing.JDialog {
    private String juego;

    /**
     * Creates new form VerJuego
     */
    public VerJuego(java.awt.Frame parent, boolean modal,String juego) {
        super(parent, modal);
        this.juego = juego;
        initComponents();
        this.setTitle(juego);
        this.obtenerJuego();
        this.obtenerPlataformas();
        this.getContentPane().setBackground(new Color (243,245,246));
    }
    
    /**
     * incicialitzam les variables al constructor (juego),ja que ho passam per parametre.
     * Cridam els metodes al constructor, de manera quan obrim el dialog es cridara als metodes
     * i es mostrarà la informació corresponent.
     */
    
    /**
     * Feim una select de tot el que hi ha a jocs on el nom de joc sigui el nom inicialitzat al constructor.
     */
    
    private void obtenerJuego() {
        Conexio mysql = new Conexio();
        Connection con = mysql.conectar();
        String sSQL = "select * from juegos where NombreJuego = '" + juego + "'";

        try {
            String multijugador = "";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sSQL);
            while (rs.next()) {

                if (rs.getString("Multijugador").equals("1")) {
                    multijugador = "Si";

                } else {
                    multijugador = "No";

                }
            }
            this.labelMultijugador.setText(multijugador);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }

    }
    /**
     * Es fa una select de plataformas per obtenir el nom d'aquestes que el joc en el que facem doble click
     * mostrara les plataformes a les que existeix.
     */
    
    private void obtenerPlataformas(){
        Conexio mysql = new Conexio();
        Connection con = mysql.conectar();
        String [] titulos = {"Plataforma"};
        String [] registro = new String[1];
        DefaultTableModel modelo = new DefaultTableModel(null,titulos);
        String sSQL = "select p.NombrePlataforma from juegos_has_plataformas jp "
            + "inner join plataformas p on jp.Plataformas_IdPlataforma = p.IdPlataforma "
            + "where Juegos_NombreJuego ='"+juego+"'";

        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sSQL);
            while (rs.next()) {
                registro[0] = rs.getString("p.NombrePlataforma");
                modelo.addRow(registro);
            }
            jTablePlataformas.setModel(modelo);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }
        
    }
    
    
         

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        labelMultijugador = new javax.swing.JLabel();
        jButtonVerPropietarios = new javax.swing.JButton();
        jButtonVerCalificaciones = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePlataformas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Multijugador");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 70, 20));

        labelMultijugador.setText("jLabel4");
        getContentPane().add(labelMultijugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 50, 20));

        jButtonVerPropietarios.setText("Ver propietarios");
        getContentPane().add(jButtonVerPropietarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 120, -1));

        jButtonVerCalificaciones.setText("Ver Calificaciones");
        jButtonVerCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerCalificacionesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVerCalificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 120, -1));

        jTablePlataformas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Plataforma"
            }
        ));
        jScrollPane1.setViewportView(jTablePlataformas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 340, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVerCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerCalificacionesActionPerformed
        // TODO add your handling code here:
        
        ComentariosJuego cj = new ComentariosJuego(new javax.swing.JFrame(), true, juego);
        cj.setVisible(true);
    }//GEN-LAST:event_jButtonVerCalificacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVerCalificaciones;
    private javax.swing.JButton jButtonVerPropietarios;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePlataformas;
    private javax.swing.JLabel labelMultijugador;
    // End of variables declaration//GEN-END:variables
}
